version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_rs
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receipts
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_rs
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin  # Persist pgAdmin settings
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .  # Assumes you have a Dockerfile in the same directory
    container_name: spring_boot_app_rs
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/receipts
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: [ "./mvnw", "spring-boot:run" ]

volumes:
  pgdata:      # Volume for PostgreSQL data
  pgadmin-data: # Volume for pgAdmin settings
